Repository TasmoAdmin/TasmoAdmin, pull requests merged in 2023-02, with the labels that each got.

#774 Fix device toggle on update
  tasmoadmin/resources/js/devices.js
Labels: fixed

#775 Corrected French translation
  tasmoadmin/lang/lang_fr.ini
Labels: fixed

#783 Streamline dev
  Makefile
  README.md
Labels: skip-changelog

#756 Move routing into application logic
  .docker/rootfs/etc/nginx/nginx-ssl.conf
  .docker/rootfs/etc/nginx/nginx.conf
  tasmoadmin/composer.json
  tasmoadmin/composer.lock
  tasmoadmin/includes/bootstrap.php
  tasmoadmin/includes/routes.php
  tasmoadmin/index.php
  tasmoadmin/pages/change_language.php
  tasmoadmin/pages/chat.php
  tasmoadmin/pages/device_action.php
  tasmoadmin/pages/device_config.php
  tasmoadmin/pages/login.php
  tasmoadmin/pages/logout.php
  tasmoadmin/resources/js/Sonoff.js
  tasmoadmin/resources/js/app.js
Labels: chore

#784 Bump minimum PHP version to 8
  .github/workflows/main.yml
  tasmoadmin/composer.json
  tasmoadmin/composer.lock
  tasmoadmin/includes/preinstallchecks.php
Labels: chore
